name: Build React Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test_deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Install Dependencies
        run: |
          npm install
        working-directory: web

      - name: Build
        run: |
          npm build
        working-directory: web
